CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(30),
    email VARCHAR(100) UNIQUE,
    password_hash VARCHAR(50),
    balance NUMERIC(10, 2) DEFAULT 10000.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crypto_prices (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    price NUMERIC(20, 10) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);